parameters:
#    forecast.example.class: Albatross\ForecastBundle\Example

services:
#    forecast.example:
#        class: %forecast.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
