parameters:
#    albatross_operation.example.class: Albatross\OperationBundle\Example

services:
#    albatross_operation.example:
#        class: %albatross_operation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
