project_homepage:
    pattern:  /list_project
    defaults: { _controller: ProjectBundle:Default:index }

view_project:
    pattern: /view_project
    defaults: { _controller: ProjectBundle:Default:view}
    
customproject_new:
    pattern:  /project/new
    defaults: { _controller: "ProjectBundle:Default:new" }