parameters:
#    albatross_daily.example.class: Albatross\DailyBundle\Example

services:
#    albatross_daily.example:
#        class: %albatross_daily.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
