parameters:
#    albatross_core.example.class: Albatross\CoreBundle\Example

services:
#    albatross_core.example:
#        class: %albatross_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
