client:
    pattern:  /
    defaults: { _controller: "AlbatrossDailyBundle:Client:index" }

client_show:
    pattern:  /{id}/show
    defaults: { _controller: "AlbatrossDailyBundle:Client:show" }

client_new:
    pattern:  /new
    defaults: { _controller: "AlbatrossDailyBundle:Client:new" }

client_create:
    pattern:  /create
    defaults: { _controller: "AlbatrossDailyBundle:Client:create" }
    requirements: { _method: post }

client_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AlbatrossDailyBundle:Client:edit" }

client_update:
    pattern:  /{id}/update
    defaults: { _controller: "AlbatrossDailyBundle:Client:update" }
    requirements: { _method: post|put }

client_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AlbatrossDailyBundle:Client:delete" }
    requirements: { _method: post|delete }