Albatross\AceBundle\Entity\FileSection:
  type: entity
  table: filesection
  uniqueConstraints:
    name:
        columns: name
  oneToMany:
    attachments:
      targetEntity: Attachments
      mappedBy: filesection
  manyToOne:
    parent:
      targetEntity: FileSection
      nullable: true
  fields:
    id:
      type: bigint
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: true
    description:
      type: text
      nullable: true
  lifecycleCallbacks: {}