parameters:
#    albatross_ace.example.class: Albatross\AceBundle\Example

services:
#    albatross_ace.example:
#        class: %albatross_ace.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
